### ISSUE TITLE
Is this available via Nuget?

### ISSUE THREAD

**Issue by k3davis** [jamesrcounts/usaddress#18]
I see there is another "fork of the codeplex version" at https://github.com/twz1234/AddressParser in Nuget, but I can't locate this one. It appears that this one has had enough updates applied since then to make it more useful.

I know this is a convenience matter but appreciate your efforts on maintaining this library in any case.

**Comment by k3davis** [comment]
So sorry for the idiotic question, I should have searched harder.

https://www.nuget.org/packages/AddressParser/

**Comment by jamesrcounts** [comment]
There is a link to the nuget package at the bottom of this repository's readme:  http://www.nuget.org/packages/AddressParser/

There is also a 4 year old fork of this repo on nuget, and the repo you linked to is called PortableAddressParser on Nuget.
