### ISSUE TITLE
Target .NET Framework

### ISSUE THREAD

**Issue by mlhDevelopment** [jamesrcounts/usaddress#23]
It appears not many additional Core libraries are used with the project, but when I added the nuget to my .NET Framework project it needed to add all these extra libraries because this project only targeted .NET Standard. If the project were updated to also target .NET Framework all those extra libraries would not be required.

I ended up not using the project because it would add about 2 dozen more references to my solution and that didn't seem worth the benefit. But I'd be interested in using it if it targeted .NET Framework.

**Comment by jamesrcounts** [comment]
Done in 1.0.3 https://www.nuget.org/packages/AddressParser/1.0.3
