### ISSUE TITLE
OutOfMemoryError parsing some addresses

### ISSUE THREAD

**Issue by lscharen** [jamesrcounts/usaddress#3]
I have been using this library successfully for quite a while, but just deployed to a production environment and the `ParseAddress` method is causing the .Net `Regex` class to trigger an `OutOfMemoryError`.  I have not seen this problem during development -- it only is happening in production.

Some sample addresses that trigger the behavior (but the exact address may not matter):

* 4611  KOLZE AVE, SCHILLER PARK, IL
* 1654  ILLINOIS ST, DES PLAINES, IL
* 11 W HUBBARD ST, CHICAGO, IL

Any suggestion of what we can look for that may be triggering this behavior? We have very limited access to the production environment, so just dropping into a debugger is not feasible.

![oom](https://cloud.githubusercontent.com/assets/752806/4443785/3acba428-47eb-11e4-9cf1-eb7c0e657f4b.png)

**Comment by tetsuo13** [comment]
I've experienced similar problems only in production. Have you tried disabling compiling regular expressions as mentioned in #1?

**Comment by lscharen** [comment]
@tetsuo13 Yes, I updated to the 0.19 nuget package anddisabled regex compilation and that seems to have worked around the issue.

**Comment by jamesrcounts** [comment]
Should we close this?  Or does someone want to submit a PR to make no-compilation the default?

**Comment by lscharen** [comment]
Closed. Curious as to the underlying cause, but having a workaround is good enough for me.
