### ISSUE TITLE
in x64 bit mode parser goes into inifinite loop 

### ISSUE THREAD

**Issue by imachabeli** [jamesrcounts/usaddress#4]
If project is built with x64 ParseAddress goes into infinite loop.
Googling suggested that there is an isuue with regex bakctracking. The only solution seems to be rewrite/simplify/split in pieces regex.

**Comment by jamesrcounts** [comment]
I have left the job where I was using this, and so I don't have a lot of time to tinker with it.  My suggestion is to use x86 if you can.  If that wont work then I'll consider a pull request as long as it came with some tests that demonstrated the problem and the fix.
