### ISSUE TITLE
PlacePattern matches partial state names

### ISSUE THREAD

**Issue by Jcw87** [jamesrcounts/usaddress#5]
Using the following address text, PlacePattern will match it incorrectly:

FT LAUDERDALE,FL,33312

It will match the city as 'FT', the state as 'LA', and nothing for the zip code. Removing the last question mark from the StatePattern seems to fix this.

**Comment by jamesrcounts** [comment]
Please create a pull request with the proposed change and an associated unit test and I'll bring it in and create an update to the NuGet package.

Thanks.

**Comment by jamesrcounts** [comment]
Pushed 0.0.20.  Awesome work, thanks.
