### ISSUE TITLE
Address incorrectly parsed

### ISSUE THREAD

**Issue by waynebrantley** [jamesrcounts/usaddress#8]
This is a valid address - you can confirm it any address verification site.
```
623 NE 5th AVE  Fort Lauderdale FL 33304
```
STREET is expected to be ``623 NE 5th AVE`` but  instead was ``623 NE 5th AVE FT``
as expected CITY is wrong too  - expected to be ``Fort Lauderdale`` but is ``Lauderdale``

**Comment by jamesrcounts** [comment]
See #7 

Surprised though because I thought #6 fixed FT Lauderdale since @Jcw87 created it in response to a Ft Lauderdale problem described in #5

**Comment by Jcw87** [comment]
My fix stopped it from interpreting the "La" in Lauderdale as the state LA (Louisiana) when using the city state zip regex by itself. I occasionally run into problems with the address 1 line not being handled correctly, but having just 1 field to check for problems on is much more manageable.
