### ISSUE TITLE
Route thrown away

### ISSUE THREAD

**Issue by waynebrantley** [jamesrcounts/usaddress#9]
This is not a verified address.

```
Route 1 Gouldsboro ME 04607
```
The STREET comes back as ``Gouldsboro ME``.
There is no STATE or CITY in the parsed results and the word ``Route`` is completely discarded.

**Comment by jamesrcounts** [comment]
See #7 

Did you know that you can edit your issues after you create them?  Not sure I really see the value in creating 1 issue per address, but if it makes you happy keep on trucking.  Otherwise, please just add the additional examples to your original issue.

**Comment by waynebrantley** [comment]
Happy to consolidate them, but thought each one might be a different fix?
You prefer them all as one?

**Comment by jamesrcounts** [comment]
Depends.  Are you planning to open many more issues?  Different PRs make sense, but having many issues will probably end up spreading out the conversation across several threads.
